import React from 'react';
import {View, Text, Image} from 'react-native';
import Header from '../../components/Header/Header';
import {KeyboardAwareScrollView} from 'react-native-keyboard-aware-scroll-view';
import Style from '../../Style/Style';
import TopHeader from '../../components/TopHeader/TopHeader';
export default function Microcustering(props) {
  return (
    <View style={Style.topcontainer}>
      <TopHeader />
      <Header name={'MICROCUSTERING'} {...props} isBack={true} />
      <KeyboardAwareScrollView>
        <View style={Style.topcontainer}>
          <Text style={Style.microcusteringtext}>
            Ionized Microcluster Alkaline Water Generator and the History of
            Producing Ionized Alkaline Water
          </Text>
          <View style={Style.microcusteringcontainer}>
            <Text>
              That are sources of electromagnetic ray of a certain wavelength,
              multi-stage microcluster ionized alkaline water generator reduces
              the 'macro clusters' found in tap water into 'micro clusters' that
              are absorbed more easily by the human body. There are many
              different wavelengths of electromagnetic radiation, such as
              visible light and ultraviolet light. Our electromagnetic wave is
              healthy to human body. It's from a natural source and is far less
              powerful than the electromagnetic wave generated by your digital
              watch. Due to its current patent pending stage in Canada and
              United States, we cannot reveal too much details about our
              electromagnetic wave and its source. Its key functionalities
              include: reduces water cluster size for better water penetration
              through cells, allowing nutrients getting into the cells and
              wastes being taken out from the cells; adjusts pH and turns acidic
              water into stable and healthy alkaline water (pH 8.0~8.5); ionizes
              water with anions and turns water into a powerful anti-oxidant;
              increases dissolved oxygen in water; retains minerals such as
              Calcium, Magnesium and Zinc that are healthy to human body in
              water; gives water smooth and sweet taste unlike any other
              filtered water; no power or energy is required; no chemical or
              synthetic additives. Because of these new characteristics, Water80
              microcluster ionized alkaline water is not just clean water, but
              also is able to help you fight over-weight, diabetes,
              constipation, high blood pressure, digestive distress, acid
              stomach, urea stones, arthritis, joint pain, blood disease, kidney
              problem and many other diseases. Click this link to learn how you
              can benefit from drinking Ionized Microcluster Alkaline Water. 17O
              NMR (Nuclear Magnetic Resonance) analysis reveals
              density/clustering of water molecules. The half line widths
              indicate the size of the molecule or water cluster as determined
              by its rate of rotation or relaxation time. Smaller the half line
              width is, less molecules per cluster contains.
            </Text>
          </View>
          <View style={Style.imagecontainermicro}>
            <Image
              source={require('../../../image/microcustering.jpg')}
              style={Style.imagesize}
            />
          </View>
          <View style={Style.microcusteringcontainer}>
            <Text>
              Revolution and History of Water Ionization and Alkalization
              Technology Water ionization and alkalization technology has gone
              through a long journey in history. Most water ionizers in the
              market today require plug-in and power via a process called
              electrolysis which separates water into two streams, acidic stream
              and alkaline stream. It was first invented in 1800 by William
              Nicholson and Johann Ritter who decomposed water into hydrogen and
              oxygen. In 1807, Humphry Davy discovered Potassium using
              electrolysis. That's right, electrolysis is a technology over 200
              years old and is widely used in smelting factories for separating
              different metal elements. Nothing has been changed much for
              electrolysis other than its scale. As electronic devices are
              getting smaller, electrolysis can be conducted in a small device
              for home uses, and that's what we see as the current water
              ionizer. It consumes electricity and generates acidic steam of
              water that is always drained and wasted at the same time. After
              more than 200 years, it's finally the time for technology
              revolution of water ionization and alkalization. Now you can take
              advantage of our patent pending technology that does not need any
              plug-in or power, is more economic, is more natural and is more
              environmentally friendly. You can compare other water ionizers
              against our Water80 system by clicking this link.{' '}
            </Text>
          </View>
        </View>
      </KeyboardAwareScrollView>
    </View>
  );
}
